# Generated by Django 3.0.5 on 2020-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200502_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to='images/', verbose_name='Изображение', width_field=400),
        ),
    ]
